Zad1_2MikolajBozecki.exe: Zad1_2MikolajBozecki.obj
	link /DEBUG /OUT:Zad1_2MikolajBozecki.exe Zad1_2MikolajBozecki.obj

Zad1_2MikolajBozecki.obj: Zad1_2MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad1_2MikolajBozecki.obj Zad1_2MikolajBozecki.cpp
