Zad10MikolajBozecki.exe: Zad10MikolajBozecki.obj
	link /DEBUG /OUT:Zad10MikolajBozecki.exe Zad10MikolajBozecki.obj

Zad10MikolajBozecki.obj: Zad10MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad10MikolajBozecki.obj Zad10MikolajBozecki.cpp
