Zad11MikolajBozecki.exe: Zad11MikolajBozecki.obj
	link /DEBUG /OUT:Zad11MikolajBozecki.exe Zad11MikolajBozecki.obj

Zad11MikolajBozecki.obj: Zad11MikolajBozecki.cpp
	cl /std:c++17 /openmp /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad11MikolajBozecki.obj Zad11MikolajBozecki.cpp