Zad15MikolajBozecki.exe: Zad15MikolajBozecki.obj
	link /DEBUG /OUT:Zad15MikolajBozecki.exe Zad15MikolajBozecki.obj

Zad15MikolajBozecki.obj: Zad15MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad15MikolajBozecki.obj Zad15MikolajBozecki.cpp
