Zad6MikolajBozecki.exe: Zad6MikolajBozecki.obj
	link /DEBUG /OUT:Zad6MikolajBozecki.exe Zad6MikolajBozecki.obj

Zad6MikolajBozecki.obj: Zad6MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad6MikolajBozecki.obj Zad6MikolajBozecki.cpp
