Zad12MikolajBozecki.exe: Zad12MikolajBozecki.obj
	link /DEBUG /OUT:Zad12MikolajBozecki.exe Zad12MikolajBozecki.obj

Zad12MikolajBozecki.obj: Zad12MikolajBozecki.cpp
	cl /std:c++17 /openmp /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad12MikolajBozecki.obj Zad12MikolajBozecki.cpp