Zad14MikolajBozecki.exe: Zad14MikolajBozecki.obj
	link /DEBUG /OUT:Zad14MikolajBozecki.exe Zad14MikolajBozecki.obj

Zad14MikolajBozecki.obj: Zad14MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad14MikolajBozecki.obj Zad14MikolajBozecki.cpp
