Zad5MikolajBozecki.exe: Zad5MikolajBozecki.obj
	link /DEBUG /OUT:Zad5MikolajBozecki.exe Zad5MikolajBozecki.obj

Zad5MikolajBozecki.obj: Zad5MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad5MikolajBozecki.obj Zad5MikolajBozecki.cpp
