Zad3_4MikolajBozecki.exe: Zad3_4MikolajBozecki.obj
	link /DEBUG /OUT:Zad3_4MikolajBozecki.exe Zad3_4MikolajBozecki.obj

Zad3_4MikolajBozecki.obj: Zad3_4MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad3_4MikolajBozecki.obj Zad3_4MikolajBozecki.cpp
