Zad7MikolajBozecki.exe: Zad7MikolajBozecki.obj
	link /DEBUG /OUT:Zad7MikolajBozecki.exe Zad7MikolajBozecki.obj

Zad7MikolajBozecki.obj: Zad7MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad7MikolajBozecki.obj Zad7MikolajBozecki.cpp
