Zad0_MikolajBozecki.exe: Zad0_MikolajBozecki.obj
	link /DEBUG /OUT:Zad0_MikolajBozecki.exe Zad0_MikolajBozecki.obj

Zad0_MikolajBozecki.obj: Zad0_MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad0_MikolajBozecki.obj Zad0_MikolajBozecki.cpp
