Zad13MikolajBozecki.exe: Zad13MikolajBozecki.obj
	link /DEBUG /OUT:Zad13MikolajBozecki.exe Zad13MikolajBozecki.obj

Zad13MikolajBozecki.obj: Zad13MikolajBozecki.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:Zad13MikolajBozecki.obj Zad13MikolajBozecki.cpp
